# Subset 10 kelas populer COCO.
# CATATAN:
# - Tidak dipakai kalau kamu pakai coco128.yaml.
# - Kalau nanti kamu download COCO 2017 full ke D:/datasets/coco2017,
#   config ini bisa dipakai untuk subset 10 kelas.

path: D:/datasets/coco2017   # ganti kalau lokasi COCO berbeda

train: train2017/images
val: val2017/images

nc: 10
names:
  - person
  - car
  - bicycle
  - dog
  - cat
  - bus
  - truck
  - traffic light
  - stop sign
  - motorcycle
