# Eksperimen advanced (E2) dengan bag-of-freebies
model: yolo11m.pt
data: configs/data_coco_subset.yaml
epochs: 100
imgsz: 640
batch: 16
workers: 8
device: 0
optimizer: SGD
lr0: 0.01
lrf: 0.05
momentum: 0.949
weight_decay: 0.0005
warmup_epochs: 5.0
warmup_momentum: 0.85
warmup_bias_lr: 0.2
box: 7.5
cls: 0.6
ema: True
cos_lr: True
patience: 15
hsv_h: 0.02
hsv_s: 0.8
hsv_v: 0.5
degrees: 5.0
translate: 0.2
scale: 0.7
shear: 2.0
perspective: 0.0008
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.15
copy_paste: 0.1
auto_augment: randaugment
amp: True
cache: ram
