# Eksperimen baseline (E1)
model: yolo11s.pt
data: configs/data_coco_subset.yaml
epochs: 50
imgsz: 640
batch: 16
workers: 8
device: 0
optimizer: SGD
lr0: 0.01
lrf: 0.1
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
ema: True
cos_lr: False
patience: 10
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.7
mixup: 0.05
copy_paste: 0.0
amp: True
cache: False
